package com.steven.television.dao;

import com.steven.television.entity.Page;
import com.steven.television.entity.TBreakRule;
import com.steven.television.entity.TBreakRuleExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TBreakRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_break_rule
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    long countByExample(TBreakRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_break_rule
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    int deleteByExample(TBreakRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_break_rule
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    int deleteByPrimaryKey(String ruleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_break_rule
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    int insert(TBreakRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_break_rule
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    int insertSelective(TBreakRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_break_rule
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    List<TBreakRule> selectByExample(TBreakRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_break_rule
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    TBreakRule selectByPrimaryKey(String ruleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_break_rule
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    int updateByExampleSelective(@Param("record") TBreakRule record, @Param("example") TBreakRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_break_rule
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    int updateByExample(@Param("record") TBreakRule record, @Param("example") TBreakRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_break_rule
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    int updateByPrimaryKeySelective(TBreakRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_break_rule
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    int updateByPrimaryKey(TBreakRule record);

    List<TBreakRule> list(Map map);
    List<TBreakRule> selectByPage(Map pager);
    int selectByPageCount(Map pager);

    List<Map> selectTelevisionOverCount(int coount);

    int updateRuleBatch(@Param("ruleIds") String ruleIds);

    List<Map> selectSupplierOverCount(int coount);

    List<Map> selectSupplierBreakRule(int count);

    List<TBreakRule> selectByCondition(Map map);
}