package com.steven.television.dao;

import com.steven.television.entity.Page;
import com.steven.television.entity.TChannel;
import com.steven.television.entity.TChannelExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    long countByExample(TChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int deleteByExample(TChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int deleteByPrimaryKey(String channelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int insert(TChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int insertSelective(TChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    List<TChannel> selectByExample(TChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    TChannel selectByPrimaryKey(String channelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") TChannel record, @Param("example") TChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByExample(@Param("record") TChannel record, @Param("example") TChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByPrimaryKeySelective(TChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByPrimaryKey(TChannel record);

    List<TChannel> list();
    List<TChannel> selectByCondition(Map map);
    List<TChannel> selectByPage(Page<TChannel> pager);
    int selectByPageCount();
}