package com.steven.television.dao;

import com.steven.television.entity.*;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    long countByExample(TFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int deleteByExample(TFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int deleteByPrimaryKey(String formId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int insert(TForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int insertSelective(TForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    List<TForm> selectByExampleWithBLOBs(TFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    List<TForm> selectByExample(TFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    TForm selectByPrimaryKey(String formId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") TForm record, @Param("example") TFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") TForm record, @Param("example") TFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByExample(@Param("record") TForm record, @Param("example") TFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByPrimaryKeySelective(TForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(TForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_form
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByPrimaryKey(TForm record);

    TForm selectByDate(String date);

    TForm selectByDateAndChannelId(@Param("date") String date, @Param("channelId") String channelId);

    List<TForm> list();

    List<TForm> selectByPage(Map pager);
    int selectByPageCount(Map pager);

    List<TForm> selectByCondition(Map map);

    List<FormVo> selectByConditionPager(Map map);

    int selectByConditionPagerCount(Map map);
}