package com.steven.television.dao;

import com.steven.television.entity.TLocation;
import com.steven.television.entity.TLocationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TLocationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_location
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    long countByExample(TLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_location
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int deleteByExample(TLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_location
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int deleteByPrimaryKey(String locationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_location
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int insert(TLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_location
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int insertSelective(TLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_location
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    List<TLocation> selectByExample(TLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_location
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    TLocation selectByPrimaryKey(String locationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_location
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") TLocation record, @Param("example") TLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_location
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByExample(@Param("record") TLocation record, @Param("example") TLocationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_location
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByPrimaryKeySelective(TLocation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_location
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByPrimaryKey(TLocation record);
}