package com.steven.television.dao;

import com.steven.television.entity.TPlay;
import com.steven.television.entity.TPlayExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TPlayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    long countByExample(TPlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    int deleteByExample(TPlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    int deleteByPrimaryKey(String playId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    int insert(TPlay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    int insertSelective(TPlay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    List<TPlay> selectByExample(TPlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    TPlay selectByPrimaryKey(String playId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") TPlay record, @Param("example") TPlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    int updateByExample(@Param("record") TPlay record, @Param("example") TPlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    int updateByPrimaryKeySelective(TPlay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    int updateByPrimaryKey(TPlay record);

    List<TPlay> selectByDateOrForm(Map map);
}