package com.steven.television.dao;

import com.steven.television.entity.Page;
import com.steven.television.entity.TSupplier;
import com.steven.television.entity.TSupplierExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TSupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    long countByExample(TSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int deleteByExample(TSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int deleteByPrimaryKey(String supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int insert(TSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int insertSelective(TSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    List<TSupplier> selectByExample(TSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    TSupplier selectByPrimaryKey(String supplierId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") TSupplier record, @Param("example") TSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByExample(@Param("record") TSupplier record, @Param("example") TSupplierExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByPrimaryKeySelective(TSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByPrimaryKey(TSupplier record);

    List<TSupplier> list();

    List<TSupplier> selectByPage(Page<TSupplier> pager);
    int selectByPageCount(Page<TSupplier> pager);
}