package com.steven.television.dao;

import com.steven.television.entity.Page;
import com.steven.television.entity.TSystem;
import com.steven.television.entity.TSystemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface TSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    long countByExample(TSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int deleteByExample(TSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int deleteByPrimaryKey(String sysId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int insert(TSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int insertSelective(TSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    List<TSystem> selectByExample(TSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    TSystem selectByPrimaryKey(String sysId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") TSystem record, @Param("example") TSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByExample(@Param("record") TSystem record, @Param("example") TSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByPrimaryKeySelective(TSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByPrimaryKey(TSystem record);

    List<TSystem> list();

    List<TSystem> selectByPage(Page<TSystem> pager);

    int selectByPageCount(Page<TSystem> pager);

    String selectValueByKey(String key);

}