package com.steven.television.dao;

import com.steven.television.entity.Page;
import com.steven.television.entity.TTelevision;
import com.steven.television.entity.TTelevisionExample;
import java.util.List;
import java.util.Map;

import com.steven.television.entity.TelevisionVo;
import org.apache.ibatis.annotations.Param;

public interface TTelevisionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    long countByExample(TTelevisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int deleteByExample(TTelevisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int deleteByPrimaryKey(String tvId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int insert(TTelevision record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int insertSelective(TTelevision record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    List<TTelevision> selectByExample(TTelevisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    TTelevision selectByPrimaryKey(String tvId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") TTelevision record, @Param("example") TTelevisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByExample(@Param("record") TTelevision record, @Param("example") TTelevisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByPrimaryKeySelective(TTelevision record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    int updateByPrimaryKey(TTelevision record);

    List<TTelevision> list(Map map);
    List<TTelevision> selectByPage(Map map);
    int selectByPageCount(Map map);


    List<TelevisionVo> televisionList(String channelId);
}