package com.steven.television.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class TBreakRule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_break_rule.rule_id
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    private String ruleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_break_rule.rule_name
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    private String ruleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_break_rule.rule_desc
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    private String ruleDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_break_rule.rule_type
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    private Integer ruleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_break_rule.tv_id
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    private String tvId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_break_rule.org_id
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    private String orgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_break_rule.status
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_break_rule.create_time
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    @JsonFormat(locale="zh", timezone="GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_break_rule.update_time
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    @JsonFormat(locale="zh", timezone="GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_break_rule.rule_id
     *
     * @return the value of t_break_rule.rule_id
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    public String getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_break_rule.rule_id
     *
     * @param ruleId the value for t_break_rule.rule_id
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    public void setRuleId(String ruleId) {
        this.ruleId = ruleId == null ? null : ruleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_break_rule.rule_name
     *
     * @return the value of t_break_rule.rule_name
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    public String getRuleName() {
        return ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_break_rule.rule_name
     *
     * @param ruleName the value for t_break_rule.rule_name
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName == null ? null : ruleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_break_rule.rule_desc
     *
     * @return the value of t_break_rule.rule_desc
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    public String getRuleDesc() {
        return ruleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_break_rule.rule_desc
     *
     * @param ruleDesc the value for t_break_rule.rule_desc
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    public void setRuleDesc(String ruleDesc) {
        this.ruleDesc = ruleDesc == null ? null : ruleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_break_rule.rule_type
     *
     * @return the value of t_break_rule.rule_type
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    public Integer getRuleType() {
        return ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_break_rule.rule_type
     *
     * @param ruleType the value for t_break_rule.rule_type
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    public void setRuleType(Integer ruleType) {
        this.ruleType = ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_break_rule.tv_id
     *
     * @return the value of t_break_rule.tv_id
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    public String getTvId() {
        return tvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_break_rule.tv_id
     *
     * @param tvId the value for t_break_rule.tv_id
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    public void setTvId(String tvId) {
        this.tvId = tvId == null ? null : tvId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_break_rule.org_id
     *
     * @return the value of t_break_rule.org_id
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_break_rule.org_id
     *
     * @param orgId the value for t_break_rule.org_id
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    public void setOrgId(String orgId) {
        this.orgId = orgId == null ? null : orgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_break_rule.status
     *
     * @return the value of t_break_rule.status
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_break_rule.status
     *
     * @param status the value for t_break_rule.status
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_break_rule.create_time
     *
     * @return the value of t_break_rule.create_time
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_break_rule.create_time
     *
     * @param createTime the value for t_break_rule.create_time
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_break_rule.update_time
     *
     * @return the value of t_break_rule.update_time
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_break_rule.update_time
     *
     * @param updateTime the value for t_break_rule.update_time
     *
     * @mbg.generated Sat Nov 14 14:33:38 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}