package com.steven.television.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class TChannel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.channel_id
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private String channelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.channel_name
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private String channelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.channel_sort
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private Integer channelSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.remark
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.status
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.create_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    @JsonFormat(locale="zh", timezone="GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_channel.update_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    @JsonFormat(locale="zh", timezone="GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.channel_id
     *
     * @return the value of t_channel.channel_id
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.channel_id
     *
     * @param channelId the value for t_channel.channel_id
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.channel_name
     *
     * @return the value of t_channel.channel_name
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.channel_name
     *
     * @param channelName the value for t_channel.channel_name
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.channel_sort
     *
     * @return the value of t_channel.channel_sort
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public Integer getChannelSort() {
        return channelSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.channel_sort
     *
     * @param channelSort the value for t_channel.channel_sort
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setChannelSort(Integer channelSort) {
        this.channelSort = channelSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.remark
     *
     * @return the value of t_channel.remark
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.remark
     *
     * @param remark the value for t_channel.remark
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.status
     *
     * @return the value of t_channel.status
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.status
     *
     * @param status the value for t_channel.status
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.create_time
     *
     * @return the value of t_channel.create_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.create_time
     *
     * @param createTime the value for t_channel.create_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_channel.update_time
     *
     * @return the value of t_channel.update_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_channel.update_time
     *
     * @param updateTime the value for t_channel.update_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}