package com.steven.television.entity;

import java.util.Date;

public class TForm {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_form.form_id
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private String formId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_form.form_date
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private Date formDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_form.watch_num
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private Integer watchNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_form.status
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_form.create_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_form.update_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_form.form_content
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private String formContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_form.form_id
     *
     * @return the value of t_form.form_id
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public String getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_form.form_id
     *
     * @param formId the value for t_form.form_id
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setFormId(String formId) {
        this.formId = formId == null ? null : formId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_form.form_date
     *
     * @return the value of t_form.form_date
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public Date getFormDate() {
        return formDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_form.form_date
     *
     * @param formDate the value for t_form.form_date
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setFormDate(Date formDate) {
        this.formDate = formDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_form.watch_num
     *
     * @return the value of t_form.watch_num
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public Integer getWatchNum() {
        return watchNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_form.watch_num
     *
     * @param watchNum the value for t_form.watch_num
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setWatchNum(Integer watchNum) {
        this.watchNum = watchNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_form.status
     *
     * @return the value of t_form.status
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_form.status
     *
     * @param status the value for t_form.status
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_form.create_time
     *
     * @return the value of t_form.create_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_form.create_time
     *
     * @param createTime the value for t_form.create_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_form.update_time
     *
     * @return the value of t_form.update_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_form.update_time
     *
     * @param updateTime the value for t_form.update_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_form.form_content
     *
     * @return the value of t_form.form_content
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public String getFormContent() {
        return formContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_form.form_content
     *
     * @param formContent the value for t_form.form_content
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setFormContent(String formContent) {
        this.formContent = formContent == null ? null : formContent.trim();
    }
}