package com.steven.television.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class TImport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import.import_id
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    private String importId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import.television_id
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    private String televisionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import.start_time
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    @JsonFormat(locale="zh", timezone="GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import.ent_time
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    @JsonFormat(locale="zh", timezone="GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date entTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import.import_length
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    private Long importLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import.import_audit
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    private Integer importAudit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import.status
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import.create_time
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    @JsonFormat(locale="zh", timezone="GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import.update_time
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    @JsonFormat(locale="zh", timezone="GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import.commit_user_id
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    private String commitUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import.commit_user_name
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    private String commitUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import.audit_user_id
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    private String auditUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import.audit_user_name
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    private String auditUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import.type
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_import.audit_content
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    private String auditContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import.import_id
     *
     * @return the value of t_import.import_id
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public String getImportId() {
        return importId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import.import_id
     *
     * @param importId the value for t_import.import_id
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public void setImportId(String importId) {
        this.importId = importId == null ? null : importId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import.television_id
     *
     * @return the value of t_import.television_id
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public String getTelevisionId() {
        return televisionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import.television_id
     *
     * @param televisionId the value for t_import.television_id
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public void setTelevisionId(String televisionId) {
        this.televisionId = televisionId == null ? null : televisionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import.start_time
     *
     * @return the value of t_import.start_time
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import.start_time
     *
     * @param startTime the value for t_import.start_time
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import.ent_time
     *
     * @return the value of t_import.ent_time
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public Date getEntTime() {
        return entTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import.ent_time
     *
     * @param entTime the value for t_import.ent_time
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public void setEntTime(Date entTime) {
        this.entTime = entTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import.import_length
     *
     * @return the value of t_import.import_length
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public Long getImportLength() {
        return importLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import.import_length
     *
     * @param importLength the value for t_import.import_length
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public void setImportLength(Long importLength) {
        this.importLength = importLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import.import_audit
     *
     * @return the value of t_import.import_audit
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public Integer getImportAudit() {
        return importAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import.import_audit
     *
     * @param importAudit the value for t_import.import_audit
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public void setImportAudit(Integer importAudit) {
        this.importAudit = importAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import.status
     *
     * @return the value of t_import.status
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import.status
     *
     * @param status the value for t_import.status
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import.create_time
     *
     * @return the value of t_import.create_time
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import.create_time
     *
     * @param createTime the value for t_import.create_time
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import.update_time
     *
     * @return the value of t_import.update_time
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import.update_time
     *
     * @param updateTime the value for t_import.update_time
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import.commit_user_id
     *
     * @return the value of t_import.commit_user_id
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public String getCommitUserId() {
        return commitUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import.commit_user_id
     *
     * @param commitUserId the value for t_import.commit_user_id
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public void setCommitUserId(String commitUserId) {
        this.commitUserId = commitUserId == null ? null : commitUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import.commit_user_name
     *
     * @return the value of t_import.commit_user_name
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public String getCommitUserName() {
        return commitUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import.commit_user_name
     *
     * @param commitUserName the value for t_import.commit_user_name
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public void setCommitUserName(String commitUserName) {
        this.commitUserName = commitUserName == null ? null : commitUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import.audit_user_id
     *
     * @return the value of t_import.audit_user_id
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public String getAuditUserId() {
        return auditUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import.audit_user_id
     *
     * @param auditUserId the value for t_import.audit_user_id
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public void setAuditUserId(String auditUserId) {
        this.auditUserId = auditUserId == null ? null : auditUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import.audit_user_name
     *
     * @return the value of t_import.audit_user_name
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public String getAuditUserName() {
        return auditUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import.audit_user_name
     *
     * @param auditUserName the value for t_import.audit_user_name
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public void setAuditUserName(String auditUserName) {
        this.auditUserName = auditUserName == null ? null : auditUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import.type
     *
     * @return the value of t_import.type
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import.type
     *
     * @param type the value for t_import.type
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_import.audit_content
     *
     * @return the value of t_import.audit_content
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public String getAuditContent() {
        return auditContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_import.audit_content
     *
     * @param auditContent the value for t_import.audit_content
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public void setAuditContent(String auditContent) {
        this.auditContent = auditContent == null ? null : auditContent.trim();
    }

    private String channelId;

    public String getChannelId() {
        return channelId;
    }

    public void setChannelId(String channelId) {
        this.channelId = channelId;
    }
}