package com.steven.television.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TImportExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_import
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_import
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_import
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_import
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public TImportExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_import
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_import
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_import
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_import
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_import
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_import
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_import
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_import
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_import
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_import
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_import
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andImportIdIsNull() {
            addCriterion("import_id is null");
            return (Criteria) this;
        }

        public Criteria andImportIdIsNotNull() {
            addCriterion("import_id is not null");
            return (Criteria) this;
        }

        public Criteria andImportIdEqualTo(String value) {
            addCriterion("import_id =", value, "importId");
            return (Criteria) this;
        }

        public Criteria andImportIdNotEqualTo(String value) {
            addCriterion("import_id <>", value, "importId");
            return (Criteria) this;
        }

        public Criteria andImportIdGreaterThan(String value) {
            addCriterion("import_id >", value, "importId");
            return (Criteria) this;
        }

        public Criteria andImportIdGreaterThanOrEqualTo(String value) {
            addCriterion("import_id >=", value, "importId");
            return (Criteria) this;
        }

        public Criteria andImportIdLessThan(String value) {
            addCriterion("import_id <", value, "importId");
            return (Criteria) this;
        }

        public Criteria andImportIdLessThanOrEqualTo(String value) {
            addCriterion("import_id <=", value, "importId");
            return (Criteria) this;
        }

        public Criteria andImportIdLike(String value) {
            addCriterion("import_id like", value, "importId");
            return (Criteria) this;
        }

        public Criteria andImportIdNotLike(String value) {
            addCriterion("import_id not like", value, "importId");
            return (Criteria) this;
        }

        public Criteria andImportIdIn(List<String> values) {
            addCriterion("import_id in", values, "importId");
            return (Criteria) this;
        }

        public Criteria andImportIdNotIn(List<String> values) {
            addCriterion("import_id not in", values, "importId");
            return (Criteria) this;
        }

        public Criteria andImportIdBetween(String value1, String value2) {
            addCriterion("import_id between", value1, value2, "importId");
            return (Criteria) this;
        }

        public Criteria andImportIdNotBetween(String value1, String value2) {
            addCriterion("import_id not between", value1, value2, "importId");
            return (Criteria) this;
        }

        public Criteria andTelevisionIdIsNull() {
            addCriterion("television_id is null");
            return (Criteria) this;
        }

        public Criteria andTelevisionIdIsNotNull() {
            addCriterion("television_id is not null");
            return (Criteria) this;
        }

        public Criteria andTelevisionIdEqualTo(String value) {
            addCriterion("television_id =", value, "televisionId");
            return (Criteria) this;
        }

        public Criteria andTelevisionIdNotEqualTo(String value) {
            addCriterion("television_id <>", value, "televisionId");
            return (Criteria) this;
        }

        public Criteria andTelevisionIdGreaterThan(String value) {
            addCriterion("television_id >", value, "televisionId");
            return (Criteria) this;
        }

        public Criteria andTelevisionIdGreaterThanOrEqualTo(String value) {
            addCriterion("television_id >=", value, "televisionId");
            return (Criteria) this;
        }

        public Criteria andTelevisionIdLessThan(String value) {
            addCriterion("television_id <", value, "televisionId");
            return (Criteria) this;
        }

        public Criteria andTelevisionIdLessThanOrEqualTo(String value) {
            addCriterion("television_id <=", value, "televisionId");
            return (Criteria) this;
        }

        public Criteria andTelevisionIdLike(String value) {
            addCriterion("television_id like", value, "televisionId");
            return (Criteria) this;
        }

        public Criteria andTelevisionIdNotLike(String value) {
            addCriterion("television_id not like", value, "televisionId");
            return (Criteria) this;
        }

        public Criteria andTelevisionIdIn(List<String> values) {
            addCriterion("television_id in", values, "televisionId");
            return (Criteria) this;
        }

        public Criteria andTelevisionIdNotIn(List<String> values) {
            addCriterion("television_id not in", values, "televisionId");
            return (Criteria) this;
        }

        public Criteria andTelevisionIdBetween(String value1, String value2) {
            addCriterion("television_id between", value1, value2, "televisionId");
            return (Criteria) this;
        }

        public Criteria andTelevisionIdNotBetween(String value1, String value2) {
            addCriterion("television_id not between", value1, value2, "televisionId");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEntTimeIsNull() {
            addCriterion("ent_time is null");
            return (Criteria) this;
        }

        public Criteria andEntTimeIsNotNull() {
            addCriterion("ent_time is not null");
            return (Criteria) this;
        }

        public Criteria andEntTimeEqualTo(Date value) {
            addCriterion("ent_time =", value, "entTime");
            return (Criteria) this;
        }

        public Criteria andEntTimeNotEqualTo(Date value) {
            addCriterion("ent_time <>", value, "entTime");
            return (Criteria) this;
        }

        public Criteria andEntTimeGreaterThan(Date value) {
            addCriterion("ent_time >", value, "entTime");
            return (Criteria) this;
        }

        public Criteria andEntTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ent_time >=", value, "entTime");
            return (Criteria) this;
        }

        public Criteria andEntTimeLessThan(Date value) {
            addCriterion("ent_time <", value, "entTime");
            return (Criteria) this;
        }

        public Criteria andEntTimeLessThanOrEqualTo(Date value) {
            addCriterion("ent_time <=", value, "entTime");
            return (Criteria) this;
        }

        public Criteria andEntTimeIn(List<Date> values) {
            addCriterion("ent_time in", values, "entTime");
            return (Criteria) this;
        }

        public Criteria andEntTimeNotIn(List<Date> values) {
            addCriterion("ent_time not in", values, "entTime");
            return (Criteria) this;
        }

        public Criteria andEntTimeBetween(Date value1, Date value2) {
            addCriterion("ent_time between", value1, value2, "entTime");
            return (Criteria) this;
        }

        public Criteria andEntTimeNotBetween(Date value1, Date value2) {
            addCriterion("ent_time not between", value1, value2, "entTime");
            return (Criteria) this;
        }

        public Criteria andImportLengthIsNull() {
            addCriterion("import_length is null");
            return (Criteria) this;
        }

        public Criteria andImportLengthIsNotNull() {
            addCriterion("import_length is not null");
            return (Criteria) this;
        }

        public Criteria andImportLengthEqualTo(Long value) {
            addCriterion("import_length =", value, "importLength");
            return (Criteria) this;
        }

        public Criteria andImportLengthNotEqualTo(Long value) {
            addCriterion("import_length <>", value, "importLength");
            return (Criteria) this;
        }

        public Criteria andImportLengthGreaterThan(Long value) {
            addCriterion("import_length >", value, "importLength");
            return (Criteria) this;
        }

        public Criteria andImportLengthGreaterThanOrEqualTo(Long value) {
            addCriterion("import_length >=", value, "importLength");
            return (Criteria) this;
        }

        public Criteria andImportLengthLessThan(Long value) {
            addCriterion("import_length <", value, "importLength");
            return (Criteria) this;
        }

        public Criteria andImportLengthLessThanOrEqualTo(Long value) {
            addCriterion("import_length <=", value, "importLength");
            return (Criteria) this;
        }

        public Criteria andImportLengthIn(List<Long> values) {
            addCriterion("import_length in", values, "importLength");
            return (Criteria) this;
        }

        public Criteria andImportLengthNotIn(List<Long> values) {
            addCriterion("import_length not in", values, "importLength");
            return (Criteria) this;
        }

        public Criteria andImportLengthBetween(Long value1, Long value2) {
            addCriterion("import_length between", value1, value2, "importLength");
            return (Criteria) this;
        }

        public Criteria andImportLengthNotBetween(Long value1, Long value2) {
            addCriterion("import_length not between", value1, value2, "importLength");
            return (Criteria) this;
        }

        public Criteria andImportAuditIsNull() {
            addCriterion("import_audit is null");
            return (Criteria) this;
        }

        public Criteria andImportAuditIsNotNull() {
            addCriterion("import_audit is not null");
            return (Criteria) this;
        }

        public Criteria andImportAuditEqualTo(Integer value) {
            addCriterion("import_audit =", value, "importAudit");
            return (Criteria) this;
        }

        public Criteria andImportAuditNotEqualTo(Integer value) {
            addCriterion("import_audit <>", value, "importAudit");
            return (Criteria) this;
        }

        public Criteria andImportAuditGreaterThan(Integer value) {
            addCriterion("import_audit >", value, "importAudit");
            return (Criteria) this;
        }

        public Criteria andImportAuditGreaterThanOrEqualTo(Integer value) {
            addCriterion("import_audit >=", value, "importAudit");
            return (Criteria) this;
        }

        public Criteria andImportAuditLessThan(Integer value) {
            addCriterion("import_audit <", value, "importAudit");
            return (Criteria) this;
        }

        public Criteria andImportAuditLessThanOrEqualTo(Integer value) {
            addCriterion("import_audit <=", value, "importAudit");
            return (Criteria) this;
        }

        public Criteria andImportAuditIn(List<Integer> values) {
            addCriterion("import_audit in", values, "importAudit");
            return (Criteria) this;
        }

        public Criteria andImportAuditNotIn(List<Integer> values) {
            addCriterion("import_audit not in", values, "importAudit");
            return (Criteria) this;
        }

        public Criteria andImportAuditBetween(Integer value1, Integer value2) {
            addCriterion("import_audit between", value1, value2, "importAudit");
            return (Criteria) this;
        }

        public Criteria andImportAuditNotBetween(Integer value1, Integer value2) {
            addCriterion("import_audit not between", value1, value2, "importAudit");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCommitUserIdIsNull() {
            addCriterion("commit_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCommitUserIdIsNotNull() {
            addCriterion("commit_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCommitUserIdEqualTo(String value) {
            addCriterion("commit_user_id =", value, "commitUserId");
            return (Criteria) this;
        }

        public Criteria andCommitUserIdNotEqualTo(String value) {
            addCriterion("commit_user_id <>", value, "commitUserId");
            return (Criteria) this;
        }

        public Criteria andCommitUserIdGreaterThan(String value) {
            addCriterion("commit_user_id >", value, "commitUserId");
            return (Criteria) this;
        }

        public Criteria andCommitUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("commit_user_id >=", value, "commitUserId");
            return (Criteria) this;
        }

        public Criteria andCommitUserIdLessThan(String value) {
            addCriterion("commit_user_id <", value, "commitUserId");
            return (Criteria) this;
        }

        public Criteria andCommitUserIdLessThanOrEqualTo(String value) {
            addCriterion("commit_user_id <=", value, "commitUserId");
            return (Criteria) this;
        }

        public Criteria andCommitUserIdLike(String value) {
            addCriterion("commit_user_id like", value, "commitUserId");
            return (Criteria) this;
        }

        public Criteria andCommitUserIdNotLike(String value) {
            addCriterion("commit_user_id not like", value, "commitUserId");
            return (Criteria) this;
        }

        public Criteria andCommitUserIdIn(List<String> values) {
            addCriterion("commit_user_id in", values, "commitUserId");
            return (Criteria) this;
        }

        public Criteria andCommitUserIdNotIn(List<String> values) {
            addCriterion("commit_user_id not in", values, "commitUserId");
            return (Criteria) this;
        }

        public Criteria andCommitUserIdBetween(String value1, String value2) {
            addCriterion("commit_user_id between", value1, value2, "commitUserId");
            return (Criteria) this;
        }

        public Criteria andCommitUserIdNotBetween(String value1, String value2) {
            addCriterion("commit_user_id not between", value1, value2, "commitUserId");
            return (Criteria) this;
        }

        public Criteria andCommitUserNameIsNull() {
            addCriterion("commit_user_name is null");
            return (Criteria) this;
        }

        public Criteria andCommitUserNameIsNotNull() {
            addCriterion("commit_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andCommitUserNameEqualTo(String value) {
            addCriterion("commit_user_name =", value, "commitUserName");
            return (Criteria) this;
        }

        public Criteria andCommitUserNameNotEqualTo(String value) {
            addCriterion("commit_user_name <>", value, "commitUserName");
            return (Criteria) this;
        }

        public Criteria andCommitUserNameGreaterThan(String value) {
            addCriterion("commit_user_name >", value, "commitUserName");
            return (Criteria) this;
        }

        public Criteria andCommitUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("commit_user_name >=", value, "commitUserName");
            return (Criteria) this;
        }

        public Criteria andCommitUserNameLessThan(String value) {
            addCriterion("commit_user_name <", value, "commitUserName");
            return (Criteria) this;
        }

        public Criteria andCommitUserNameLessThanOrEqualTo(String value) {
            addCriterion("commit_user_name <=", value, "commitUserName");
            return (Criteria) this;
        }

        public Criteria andCommitUserNameLike(String value) {
            addCriterion("commit_user_name like", value, "commitUserName");
            return (Criteria) this;
        }

        public Criteria andCommitUserNameNotLike(String value) {
            addCriterion("commit_user_name not like", value, "commitUserName");
            return (Criteria) this;
        }

        public Criteria andCommitUserNameIn(List<String> values) {
            addCriterion("commit_user_name in", values, "commitUserName");
            return (Criteria) this;
        }

        public Criteria andCommitUserNameNotIn(List<String> values) {
            addCriterion("commit_user_name not in", values, "commitUserName");
            return (Criteria) this;
        }

        public Criteria andCommitUserNameBetween(String value1, String value2) {
            addCriterion("commit_user_name between", value1, value2, "commitUserName");
            return (Criteria) this;
        }

        public Criteria andCommitUserNameNotBetween(String value1, String value2) {
            addCriterion("commit_user_name not between", value1, value2, "commitUserName");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdIsNull() {
            addCriterion("audit_user_id is null");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdIsNotNull() {
            addCriterion("audit_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdEqualTo(String value) {
            addCriterion("audit_user_id =", value, "auditUserId");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdNotEqualTo(String value) {
            addCriterion("audit_user_id <>", value, "auditUserId");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdGreaterThan(String value) {
            addCriterion("audit_user_id >", value, "auditUserId");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("audit_user_id >=", value, "auditUserId");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdLessThan(String value) {
            addCriterion("audit_user_id <", value, "auditUserId");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdLessThanOrEqualTo(String value) {
            addCriterion("audit_user_id <=", value, "auditUserId");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdLike(String value) {
            addCriterion("audit_user_id like", value, "auditUserId");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdNotLike(String value) {
            addCriterion("audit_user_id not like", value, "auditUserId");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdIn(List<String> values) {
            addCriterion("audit_user_id in", values, "auditUserId");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdNotIn(List<String> values) {
            addCriterion("audit_user_id not in", values, "auditUserId");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdBetween(String value1, String value2) {
            addCriterion("audit_user_id between", value1, value2, "auditUserId");
            return (Criteria) this;
        }

        public Criteria andAuditUserIdNotBetween(String value1, String value2) {
            addCriterion("audit_user_id not between", value1, value2, "auditUserId");
            return (Criteria) this;
        }

        public Criteria andAuditUserNameIsNull() {
            addCriterion("audit_user_name is null");
            return (Criteria) this;
        }

        public Criteria andAuditUserNameIsNotNull() {
            addCriterion("audit_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andAuditUserNameEqualTo(String value) {
            addCriterion("audit_user_name =", value, "auditUserName");
            return (Criteria) this;
        }

        public Criteria andAuditUserNameNotEqualTo(String value) {
            addCriterion("audit_user_name <>", value, "auditUserName");
            return (Criteria) this;
        }

        public Criteria andAuditUserNameGreaterThan(String value) {
            addCriterion("audit_user_name >", value, "auditUserName");
            return (Criteria) this;
        }

        public Criteria andAuditUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("audit_user_name >=", value, "auditUserName");
            return (Criteria) this;
        }

        public Criteria andAuditUserNameLessThan(String value) {
            addCriterion("audit_user_name <", value, "auditUserName");
            return (Criteria) this;
        }

        public Criteria andAuditUserNameLessThanOrEqualTo(String value) {
            addCriterion("audit_user_name <=", value, "auditUserName");
            return (Criteria) this;
        }

        public Criteria andAuditUserNameLike(String value) {
            addCriterion("audit_user_name like", value, "auditUserName");
            return (Criteria) this;
        }

        public Criteria andAuditUserNameNotLike(String value) {
            addCriterion("audit_user_name not like", value, "auditUserName");
            return (Criteria) this;
        }

        public Criteria andAuditUserNameIn(List<String> values) {
            addCriterion("audit_user_name in", values, "auditUserName");
            return (Criteria) this;
        }

        public Criteria andAuditUserNameNotIn(List<String> values) {
            addCriterion("audit_user_name not in", values, "auditUserName");
            return (Criteria) this;
        }

        public Criteria andAuditUserNameBetween(String value1, String value2) {
            addCriterion("audit_user_name between", value1, value2, "auditUserName");
            return (Criteria) this;
        }

        public Criteria andAuditUserNameNotBetween(String value1, String value2) {
            addCriterion("audit_user_name not between", value1, value2, "auditUserName");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andAuditContentIsNull() {
            addCriterion("audit_content is null");
            return (Criteria) this;
        }

        public Criteria andAuditContentIsNotNull() {
            addCriterion("audit_content is not null");
            return (Criteria) this;
        }

        public Criteria andAuditContentEqualTo(String value) {
            addCriterion("audit_content =", value, "auditContent");
            return (Criteria) this;
        }

        public Criteria andAuditContentNotEqualTo(String value) {
            addCriterion("audit_content <>", value, "auditContent");
            return (Criteria) this;
        }

        public Criteria andAuditContentGreaterThan(String value) {
            addCriterion("audit_content >", value, "auditContent");
            return (Criteria) this;
        }

        public Criteria andAuditContentGreaterThanOrEqualTo(String value) {
            addCriterion("audit_content >=", value, "auditContent");
            return (Criteria) this;
        }

        public Criteria andAuditContentLessThan(String value) {
            addCriterion("audit_content <", value, "auditContent");
            return (Criteria) this;
        }

        public Criteria andAuditContentLessThanOrEqualTo(String value) {
            addCriterion("audit_content <=", value, "auditContent");
            return (Criteria) this;
        }

        public Criteria andAuditContentLike(String value) {
            addCriterion("audit_content like", value, "auditContent");
            return (Criteria) this;
        }

        public Criteria andAuditContentNotLike(String value) {
            addCriterion("audit_content not like", value, "auditContent");
            return (Criteria) this;
        }

        public Criteria andAuditContentIn(List<String> values) {
            addCriterion("audit_content in", values, "auditContent");
            return (Criteria) this;
        }

        public Criteria andAuditContentNotIn(List<String> values) {
            addCriterion("audit_content not in", values, "auditContent");
            return (Criteria) this;
        }

        public Criteria andAuditContentBetween(String value1, String value2) {
            addCriterion("audit_content between", value1, value2, "auditContent");
            return (Criteria) this;
        }

        public Criteria andAuditContentNotBetween(String value1, String value2) {
            addCriterion("audit_content not between", value1, value2, "auditContent");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_import
     *
     * @mbg.generated do_not_delete_during_merge Thu Nov 19 00:16:45 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_import
     *
     * @mbg.generated Thu Nov 19 00:16:45 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}