package com.steven.television.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class TLocation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_location.location_id
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private String locationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_location.location_name
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private String locationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_location.location_type
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private Integer locationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_location.location_addr
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private String locationAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_location.status
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_location.create_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_location.update_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_location.location_id
     *
     * @return the value of t_location.location_id
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public String getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_location.location_id
     *
     * @param locationId the value for t_location.location_id
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setLocationId(String locationId) {
        this.locationId = locationId == null ? null : locationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_location.location_name
     *
     * @return the value of t_location.location_name
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public String getLocationName() {
        return locationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_location.location_name
     *
     * @param locationName the value for t_location.location_name
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setLocationName(String locationName) {
        this.locationName = locationName == null ? null : locationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_location.location_type
     *
     * @return the value of t_location.location_type
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public Integer getLocationType() {
        return locationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_location.location_type
     *
     * @param locationType the value for t_location.location_type
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setLocationType(Integer locationType) {
        this.locationType = locationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_location.location_addr
     *
     * @return the value of t_location.location_addr
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public String getLocationAddr() {
        return locationAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_location.location_addr
     *
     * @param locationAddr the value for t_location.location_addr
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setLocationAddr(String locationAddr) {
        this.locationAddr = locationAddr == null ? null : locationAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_location.status
     *
     * @return the value of t_location.status
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_location.status
     *
     * @param status the value for t_location.status
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_location.create_time
     *
     * @return the value of t_location.create_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_location.create_time
     *
     * @param createTime the value for t_location.create_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_location.update_time
     *
     * @return the value of t_location.update_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_location.update_time
     *
     * @param updateTime the value for t_location.update_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}