package com.steven.television.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TPlayExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public TPlayExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPlayIdIsNull() {
            addCriterion("play_id is null");
            return (Criteria) this;
        }

        public Criteria andPlayIdIsNotNull() {
            addCriterion("play_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlayIdEqualTo(String value) {
            addCriterion("play_id =", value, "playId");
            return (Criteria) this;
        }

        public Criteria andPlayIdNotEqualTo(String value) {
            addCriterion("play_id <>", value, "playId");
            return (Criteria) this;
        }

        public Criteria andPlayIdGreaterThan(String value) {
            addCriterion("play_id >", value, "playId");
            return (Criteria) this;
        }

        public Criteria andPlayIdGreaterThanOrEqualTo(String value) {
            addCriterion("play_id >=", value, "playId");
            return (Criteria) this;
        }

        public Criteria andPlayIdLessThan(String value) {
            addCriterion("play_id <", value, "playId");
            return (Criteria) this;
        }

        public Criteria andPlayIdLessThanOrEqualTo(String value) {
            addCriterion("play_id <=", value, "playId");
            return (Criteria) this;
        }

        public Criteria andPlayIdLike(String value) {
            addCriterion("play_id like", value, "playId");
            return (Criteria) this;
        }

        public Criteria andPlayIdNotLike(String value) {
            addCriterion("play_id not like", value, "playId");
            return (Criteria) this;
        }

        public Criteria andPlayIdIn(List<String> values) {
            addCriterion("play_id in", values, "playId");
            return (Criteria) this;
        }

        public Criteria andPlayIdNotIn(List<String> values) {
            addCriterion("play_id not in", values, "playId");
            return (Criteria) this;
        }

        public Criteria andPlayIdBetween(String value1, String value2) {
            addCriterion("play_id between", value1, value2, "playId");
            return (Criteria) this;
        }

        public Criteria andPlayIdNotBetween(String value1, String value2) {
            addCriterion("play_id not between", value1, value2, "playId");
            return (Criteria) this;
        }

        public Criteria andPlayFormIsNull() {
            addCriterion("play_form is null");
            return (Criteria) this;
        }

        public Criteria andPlayFormIsNotNull() {
            addCriterion("play_form is not null");
            return (Criteria) this;
        }

        public Criteria andPlayFormEqualTo(String value) {
            addCriterion("play_form =", value, "playForm");
            return (Criteria) this;
        }

        public Criteria andPlayFormNotEqualTo(String value) {
            addCriterion("play_form <>", value, "playForm");
            return (Criteria) this;
        }

        public Criteria andPlayFormGreaterThan(String value) {
            addCriterion("play_form >", value, "playForm");
            return (Criteria) this;
        }

        public Criteria andPlayFormGreaterThanOrEqualTo(String value) {
            addCriterion("play_form >=", value, "playForm");
            return (Criteria) this;
        }

        public Criteria andPlayFormLessThan(String value) {
            addCriterion("play_form <", value, "playForm");
            return (Criteria) this;
        }

        public Criteria andPlayFormLessThanOrEqualTo(String value) {
            addCriterion("play_form <=", value, "playForm");
            return (Criteria) this;
        }

        public Criteria andPlayFormLike(String value) {
            addCriterion("play_form like", value, "playForm");
            return (Criteria) this;
        }

        public Criteria andPlayFormNotLike(String value) {
            addCriterion("play_form not like", value, "playForm");
            return (Criteria) this;
        }

        public Criteria andPlayFormIn(List<String> values) {
            addCriterion("play_form in", values, "playForm");
            return (Criteria) this;
        }

        public Criteria andPlayFormNotIn(List<String> values) {
            addCriterion("play_form not in", values, "playForm");
            return (Criteria) this;
        }

        public Criteria andPlayFormBetween(String value1, String value2) {
            addCriterion("play_form between", value1, value2, "playForm");
            return (Criteria) this;
        }

        public Criteria andPlayFormNotBetween(String value1, String value2) {
            addCriterion("play_form not between", value1, value2, "playForm");
            return (Criteria) this;
        }

        public Criteria andPlayDateIsNull() {
            addCriterion("play_date is null");
            return (Criteria) this;
        }

        public Criteria andPlayDateIsNotNull() {
            addCriterion("play_date is not null");
            return (Criteria) this;
        }

        public Criteria andPlayDateEqualTo(Date value) {
            addCriterion("play_date =", value, "playDate");
            return (Criteria) this;
        }

        public Criteria andPlayDateNotEqualTo(Date value) {
            addCriterion("play_date <>", value, "playDate");
            return (Criteria) this;
        }

        public Criteria andPlayDateGreaterThan(Date value) {
            addCriterion("play_date >", value, "playDate");
            return (Criteria) this;
        }

        public Criteria andPlayDateGreaterThanOrEqualTo(Date value) {
            addCriterion("play_date >=", value, "playDate");
            return (Criteria) this;
        }

        public Criteria andPlayDateLessThan(Date value) {
            addCriterion("play_date <", value, "playDate");
            return (Criteria) this;
        }

        public Criteria andPlayDateLessThanOrEqualTo(Date value) {
            addCriterion("play_date <=", value, "playDate");
            return (Criteria) this;
        }

        public Criteria andPlayDateIn(List<Date> values) {
            addCriterion("play_date in", values, "playDate");
            return (Criteria) this;
        }

        public Criteria andPlayDateNotIn(List<Date> values) {
            addCriterion("play_date not in", values, "playDate");
            return (Criteria) this;
        }

        public Criteria andPlayDateBetween(Date value1, Date value2) {
            addCriterion("play_date between", value1, value2, "playDate");
            return (Criteria) this;
        }

        public Criteria andPlayDateNotBetween(Date value1, Date value2) {
            addCriterion("play_date not between", value1, value2, "playDate");
            return (Criteria) this;
        }

        public Criteria andPlayStartIsNull() {
            addCriterion("play_start is null");
            return (Criteria) this;
        }

        public Criteria andPlayStartIsNotNull() {
            addCriterion("play_start is not null");
            return (Criteria) this;
        }

        public Criteria andPlayStartEqualTo(Date value) {
            addCriterion("play_start =", value, "playStart");
            return (Criteria) this;
        }

        public Criteria andPlayStartNotEqualTo(Date value) {
            addCriterion("play_start <>", value, "playStart");
            return (Criteria) this;
        }

        public Criteria andPlayStartGreaterThan(Date value) {
            addCriterion("play_start >", value, "playStart");
            return (Criteria) this;
        }

        public Criteria andPlayStartGreaterThanOrEqualTo(Date value) {
            addCriterion("play_start >=", value, "playStart");
            return (Criteria) this;
        }

        public Criteria andPlayStartLessThan(Date value) {
            addCriterion("play_start <", value, "playStart");
            return (Criteria) this;
        }

        public Criteria andPlayStartLessThanOrEqualTo(Date value) {
            addCriterion("play_start <=", value, "playStart");
            return (Criteria) this;
        }

        public Criteria andPlayStartIn(List<Date> values) {
            addCriterion("play_start in", values, "playStart");
            return (Criteria) this;
        }

        public Criteria andPlayStartNotIn(List<Date> values) {
            addCriterion("play_start not in", values, "playStart");
            return (Criteria) this;
        }

        public Criteria andPlayStartBetween(Date value1, Date value2) {
            addCriterion("play_start between", value1, value2, "playStart");
            return (Criteria) this;
        }

        public Criteria andPlayStartNotBetween(Date value1, Date value2) {
            addCriterion("play_start not between", value1, value2, "playStart");
            return (Criteria) this;
        }

        public Criteria andPlayEndIsNull() {
            addCriterion("play_end is null");
            return (Criteria) this;
        }

        public Criteria andPlayEndIsNotNull() {
            addCriterion("play_end is not null");
            return (Criteria) this;
        }

        public Criteria andPlayEndEqualTo(Date value) {
            addCriterion("play_end =", value, "playEnd");
            return (Criteria) this;
        }

        public Criteria andPlayEndNotEqualTo(Date value) {
            addCriterion("play_end <>", value, "playEnd");
            return (Criteria) this;
        }

        public Criteria andPlayEndGreaterThan(Date value) {
            addCriterion("play_end >", value, "playEnd");
            return (Criteria) this;
        }

        public Criteria andPlayEndGreaterThanOrEqualTo(Date value) {
            addCriterion("play_end >=", value, "playEnd");
            return (Criteria) this;
        }

        public Criteria andPlayEndLessThan(Date value) {
            addCriterion("play_end <", value, "playEnd");
            return (Criteria) this;
        }

        public Criteria andPlayEndLessThanOrEqualTo(Date value) {
            addCriterion("play_end <=", value, "playEnd");
            return (Criteria) this;
        }

        public Criteria andPlayEndIn(List<Date> values) {
            addCriterion("play_end in", values, "playEnd");
            return (Criteria) this;
        }

        public Criteria andPlayEndNotIn(List<Date> values) {
            addCriterion("play_end not in", values, "playEnd");
            return (Criteria) this;
        }

        public Criteria andPlayEndBetween(Date value1, Date value2) {
            addCriterion("play_end between", value1, value2, "playEnd");
            return (Criteria) this;
        }

        public Criteria andPlayEndNotBetween(Date value1, Date value2) {
            addCriterion("play_end not between", value1, value2, "playEnd");
            return (Criteria) this;
        }

        public Criteria andPlayLengthIsNull() {
            addCriterion("play_length is null");
            return (Criteria) this;
        }

        public Criteria andPlayLengthIsNotNull() {
            addCriterion("play_length is not null");
            return (Criteria) this;
        }

        public Criteria andPlayLengthEqualTo(Long value) {
            addCriterion("play_length =", value, "playLength");
            return (Criteria) this;
        }

        public Criteria andPlayLengthNotEqualTo(Long value) {
            addCriterion("play_length <>", value, "playLength");
            return (Criteria) this;
        }

        public Criteria andPlayLengthGreaterThan(Long value) {
            addCriterion("play_length >", value, "playLength");
            return (Criteria) this;
        }

        public Criteria andPlayLengthGreaterThanOrEqualTo(Long value) {
            addCriterion("play_length >=", value, "playLength");
            return (Criteria) this;
        }

        public Criteria andPlayLengthLessThan(Long value) {
            addCriterion("play_length <", value, "playLength");
            return (Criteria) this;
        }

        public Criteria andPlayLengthLessThanOrEqualTo(Long value) {
            addCriterion("play_length <=", value, "playLength");
            return (Criteria) this;
        }

        public Criteria andPlayLengthIn(List<Long> values) {
            addCriterion("play_length in", values, "playLength");
            return (Criteria) this;
        }

        public Criteria andPlayLengthNotIn(List<Long> values) {
            addCriterion("play_length not in", values, "playLength");
            return (Criteria) this;
        }

        public Criteria andPlayLengthBetween(Long value1, Long value2) {
            addCriterion("play_length between", value1, value2, "playLength");
            return (Criteria) this;
        }

        public Criteria andPlayLengthNotBetween(Long value1, Long value2) {
            addCriterion("play_length not between", value1, value2, "playLength");
            return (Criteria) this;
        }

        public Criteria andPlayTvIdIsNull() {
            addCriterion("play_tv_id is null");
            return (Criteria) this;
        }

        public Criteria andPlayTvIdIsNotNull() {
            addCriterion("play_tv_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlayTvIdEqualTo(String value) {
            addCriterion("play_tv_id =", value, "playTvId");
            return (Criteria) this;
        }

        public Criteria andPlayTvIdNotEqualTo(String value) {
            addCriterion("play_tv_id <>", value, "playTvId");
            return (Criteria) this;
        }

        public Criteria andPlayTvIdGreaterThan(String value) {
            addCriterion("play_tv_id >", value, "playTvId");
            return (Criteria) this;
        }

        public Criteria andPlayTvIdGreaterThanOrEqualTo(String value) {
            addCriterion("play_tv_id >=", value, "playTvId");
            return (Criteria) this;
        }

        public Criteria andPlayTvIdLessThan(String value) {
            addCriterion("play_tv_id <", value, "playTvId");
            return (Criteria) this;
        }

        public Criteria andPlayTvIdLessThanOrEqualTo(String value) {
            addCriterion("play_tv_id <=", value, "playTvId");
            return (Criteria) this;
        }

        public Criteria andPlayTvIdLike(String value) {
            addCriterion("play_tv_id like", value, "playTvId");
            return (Criteria) this;
        }

        public Criteria andPlayTvIdNotLike(String value) {
            addCriterion("play_tv_id not like", value, "playTvId");
            return (Criteria) this;
        }

        public Criteria andPlayTvIdIn(List<String> values) {
            addCriterion("play_tv_id in", values, "playTvId");
            return (Criteria) this;
        }

        public Criteria andPlayTvIdNotIn(List<String> values) {
            addCriterion("play_tv_id not in", values, "playTvId");
            return (Criteria) this;
        }

        public Criteria andPlayTvIdBetween(String value1, String value2) {
            addCriterion("play_tv_id between", value1, value2, "playTvId");
            return (Criteria) this;
        }

        public Criteria andPlayTvIdNotBetween(String value1, String value2) {
            addCriterion("play_tv_id not between", value1, value2, "playTvId");
            return (Criteria) this;
        }

        public Criteria andPlayTvNameIsNull() {
            addCriterion("play_tv_name is null");
            return (Criteria) this;
        }

        public Criteria andPlayTvNameIsNotNull() {
            addCriterion("play_tv_name is not null");
            return (Criteria) this;
        }

        public Criteria andPlayTvNameEqualTo(String value) {
            addCriterion("play_tv_name =", value, "playTvName");
            return (Criteria) this;
        }

        public Criteria andPlayTvNameNotEqualTo(String value) {
            addCriterion("play_tv_name <>", value, "playTvName");
            return (Criteria) this;
        }

        public Criteria andPlayTvNameGreaterThan(String value) {
            addCriterion("play_tv_name >", value, "playTvName");
            return (Criteria) this;
        }

        public Criteria andPlayTvNameGreaterThanOrEqualTo(String value) {
            addCriterion("play_tv_name >=", value, "playTvName");
            return (Criteria) this;
        }

        public Criteria andPlayTvNameLessThan(String value) {
            addCriterion("play_tv_name <", value, "playTvName");
            return (Criteria) this;
        }

        public Criteria andPlayTvNameLessThanOrEqualTo(String value) {
            addCriterion("play_tv_name <=", value, "playTvName");
            return (Criteria) this;
        }

        public Criteria andPlayTvNameLike(String value) {
            addCriterion("play_tv_name like", value, "playTvName");
            return (Criteria) this;
        }

        public Criteria andPlayTvNameNotLike(String value) {
            addCriterion("play_tv_name not like", value, "playTvName");
            return (Criteria) this;
        }

        public Criteria andPlayTvNameIn(List<String> values) {
            addCriterion("play_tv_name in", values, "playTvName");
            return (Criteria) this;
        }

        public Criteria andPlayTvNameNotIn(List<String> values) {
            addCriterion("play_tv_name not in", values, "playTvName");
            return (Criteria) this;
        }

        public Criteria andPlayTvNameBetween(String value1, String value2) {
            addCriterion("play_tv_name between", value1, value2, "playTvName");
            return (Criteria) this;
        }

        public Criteria andPlayTvNameNotBetween(String value1, String value2) {
            addCriterion("play_tv_name not between", value1, value2, "playTvName");
            return (Criteria) this;
        }

        public Criteria andPlayTvDescIsNull() {
            addCriterion("play_tv_desc is null");
            return (Criteria) this;
        }

        public Criteria andPlayTvDescIsNotNull() {
            addCriterion("play_tv_desc is not null");
            return (Criteria) this;
        }

        public Criteria andPlayTvDescEqualTo(String value) {
            addCriterion("play_tv_desc =", value, "playTvDesc");
            return (Criteria) this;
        }

        public Criteria andPlayTvDescNotEqualTo(String value) {
            addCriterion("play_tv_desc <>", value, "playTvDesc");
            return (Criteria) this;
        }

        public Criteria andPlayTvDescGreaterThan(String value) {
            addCriterion("play_tv_desc >", value, "playTvDesc");
            return (Criteria) this;
        }

        public Criteria andPlayTvDescGreaterThanOrEqualTo(String value) {
            addCriterion("play_tv_desc >=", value, "playTvDesc");
            return (Criteria) this;
        }

        public Criteria andPlayTvDescLessThan(String value) {
            addCriterion("play_tv_desc <", value, "playTvDesc");
            return (Criteria) this;
        }

        public Criteria andPlayTvDescLessThanOrEqualTo(String value) {
            addCriterion("play_tv_desc <=", value, "playTvDesc");
            return (Criteria) this;
        }

        public Criteria andPlayTvDescLike(String value) {
            addCriterion("play_tv_desc like", value, "playTvDesc");
            return (Criteria) this;
        }

        public Criteria andPlayTvDescNotLike(String value) {
            addCriterion("play_tv_desc not like", value, "playTvDesc");
            return (Criteria) this;
        }

        public Criteria andPlayTvDescIn(List<String> values) {
            addCriterion("play_tv_desc in", values, "playTvDesc");
            return (Criteria) this;
        }

        public Criteria andPlayTvDescNotIn(List<String> values) {
            addCriterion("play_tv_desc not in", values, "playTvDesc");
            return (Criteria) this;
        }

        public Criteria andPlayTvDescBetween(String value1, String value2) {
            addCriterion("play_tv_desc between", value1, value2, "playTvDesc");
            return (Criteria) this;
        }

        public Criteria andPlayTvDescNotBetween(String value1, String value2) {
            addCriterion("play_tv_desc not between", value1, value2, "playTvDesc");
            return (Criteria) this;
        }

        public Criteria andPlayScreenIsNull() {
            addCriterion("play_screen is null");
            return (Criteria) this;
        }

        public Criteria andPlayScreenIsNotNull() {
            addCriterion("play_screen is not null");
            return (Criteria) this;
        }

        public Criteria andPlayScreenEqualTo(String value) {
            addCriterion("play_screen =", value, "playScreen");
            return (Criteria) this;
        }

        public Criteria andPlayScreenNotEqualTo(String value) {
            addCriterion("play_screen <>", value, "playScreen");
            return (Criteria) this;
        }

        public Criteria andPlayScreenGreaterThan(String value) {
            addCriterion("play_screen >", value, "playScreen");
            return (Criteria) this;
        }

        public Criteria andPlayScreenGreaterThanOrEqualTo(String value) {
            addCriterion("play_screen >=", value, "playScreen");
            return (Criteria) this;
        }

        public Criteria andPlayScreenLessThan(String value) {
            addCriterion("play_screen <", value, "playScreen");
            return (Criteria) this;
        }

        public Criteria andPlayScreenLessThanOrEqualTo(String value) {
            addCriterion("play_screen <=", value, "playScreen");
            return (Criteria) this;
        }

        public Criteria andPlayScreenLike(String value) {
            addCriterion("play_screen like", value, "playScreen");
            return (Criteria) this;
        }

        public Criteria andPlayScreenNotLike(String value) {
            addCriterion("play_screen not like", value, "playScreen");
            return (Criteria) this;
        }

        public Criteria andPlayScreenIn(List<String> values) {
            addCriterion("play_screen in", values, "playScreen");
            return (Criteria) this;
        }

        public Criteria andPlayScreenNotIn(List<String> values) {
            addCriterion("play_screen not in", values, "playScreen");
            return (Criteria) this;
        }

        public Criteria andPlayScreenBetween(String value1, String value2) {
            addCriterion("play_screen between", value1, value2, "playScreen");
            return (Criteria) this;
        }

        public Criteria andPlayScreenNotBetween(String value1, String value2) {
            addCriterion("play_screen not between", value1, value2, "playScreen");
            return (Criteria) this;
        }

        public Criteria andPlayVideoIsNull() {
            addCriterion("play_video is null");
            return (Criteria) this;
        }

        public Criteria andPlayVideoIsNotNull() {
            addCriterion("play_video is not null");
            return (Criteria) this;
        }

        public Criteria andPlayVideoEqualTo(String value) {
            addCriterion("play_video =", value, "playVideo");
            return (Criteria) this;
        }

        public Criteria andPlayVideoNotEqualTo(String value) {
            addCriterion("play_video <>", value, "playVideo");
            return (Criteria) this;
        }

        public Criteria andPlayVideoGreaterThan(String value) {
            addCriterion("play_video >", value, "playVideo");
            return (Criteria) this;
        }

        public Criteria andPlayVideoGreaterThanOrEqualTo(String value) {
            addCriterion("play_video >=", value, "playVideo");
            return (Criteria) this;
        }

        public Criteria andPlayVideoLessThan(String value) {
            addCriterion("play_video <", value, "playVideo");
            return (Criteria) this;
        }

        public Criteria andPlayVideoLessThanOrEqualTo(String value) {
            addCriterion("play_video <=", value, "playVideo");
            return (Criteria) this;
        }

        public Criteria andPlayVideoLike(String value) {
            addCriterion("play_video like", value, "playVideo");
            return (Criteria) this;
        }

        public Criteria andPlayVideoNotLike(String value) {
            addCriterion("play_video not like", value, "playVideo");
            return (Criteria) this;
        }

        public Criteria andPlayVideoIn(List<String> values) {
            addCriterion("play_video in", values, "playVideo");
            return (Criteria) this;
        }

        public Criteria andPlayVideoNotIn(List<String> values) {
            addCriterion("play_video not in", values, "playVideo");
            return (Criteria) this;
        }

        public Criteria andPlayVideoBetween(String value1, String value2) {
            addCriterion("play_video between", value1, value2, "playVideo");
            return (Criteria) this;
        }

        public Criteria andPlayVideoNotBetween(String value1, String value2) {
            addCriterion("play_video not between", value1, value2, "playVideo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_play
     *
     * @mbg.generated do_not_delete_during_merge Wed Nov 18 02:00:18 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_play
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}