package com.steven.television.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class TPlay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_play.play_id
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    private String playId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_play.play_form
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    private String playForm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_play.play_date
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    @JsonFormat(locale="zh", timezone="GMT+8", pattern = "yyy-MM-dd")
    private Date playDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_play.play_start
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    @JsonFormat(locale="zh", timezone="GMT+8", pattern = "yyy-MM-dd HH:mm:ss")
    private Date playStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_play.play_end
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    @JsonFormat(locale="zh", timezone="GMT+8", pattern = "yyy-MM-dd HH:mm:ss")
    private Date playEnd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_play.play_length
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    private Long playLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_play.play_tv_id
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    private String playTvId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_play.play_tv_name
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    private String playTvName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_play.play_tv_desc
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    private String playTvDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_play.play_screen
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    private String playScreen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_play.play_video
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    private String playVideo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_play.play_id
     *
     * @return the value of t_play.play_id
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public String getPlayId() {
        return playId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_play.play_id
     *
     * @param playId the value for t_play.play_id
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public void setPlayId(String playId) {
        this.playId = playId == null ? null : playId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_play.play_form
     *
     * @return the value of t_play.play_form
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public String getPlayForm() {
        return playForm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_play.play_form
     *
     * @param playForm the value for t_play.play_form
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public void setPlayForm(String playForm) {
        this.playForm = playForm == null ? null : playForm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_play.play_date
     *
     * @return the value of t_play.play_date
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public Date getPlayDate() {
        return playDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_play.play_date
     *
     * @param playDate the value for t_play.play_date
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public void setPlayDate(Date playDate) {
        this.playDate = playDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_play.play_start
     *
     * @return the value of t_play.play_start
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public Date getPlayStart() {
        return playStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_play.play_start
     *
     * @param playStart the value for t_play.play_start
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public void setPlayStart(Date playStart) {
        this.playStart = playStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_play.play_end
     *
     * @return the value of t_play.play_end
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public Date getPlayEnd() {
        return playEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_play.play_end
     *
     * @param playEnd the value for t_play.play_end
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public void setPlayEnd(Date playEnd) {
        this.playEnd = playEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_play.play_length
     *
     * @return the value of t_play.play_length
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public Long getPlayLength() {
        return playLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_play.play_length
     *
     * @param playLength the value for t_play.play_length
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public void setPlayLength(Long playLength) {
        this.playLength = playLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_play.play_tv_id
     *
     * @return the value of t_play.play_tv_id
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public String getPlayTvId() {
        return playTvId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_play.play_tv_id
     *
     * @param playTvId the value for t_play.play_tv_id
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public void setPlayTvId(String playTvId) {
        this.playTvId = playTvId == null ? null : playTvId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_play.play_tv_name
     *
     * @return the value of t_play.play_tv_name
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public String getPlayTvName() {
        return playTvName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_play.play_tv_name
     *
     * @param playTvName the value for t_play.play_tv_name
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public void setPlayTvName(String playTvName) {
        this.playTvName = playTvName == null ? null : playTvName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_play.play_tv_desc
     *
     * @return the value of t_play.play_tv_desc
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public String getPlayTvDesc() {
        return playTvDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_play.play_tv_desc
     *
     * @param playTvDesc the value for t_play.play_tv_desc
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public void setPlayTvDesc(String playTvDesc) {
        this.playTvDesc = playTvDesc == null ? null : playTvDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_play.play_screen
     *
     * @return the value of t_play.play_screen
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public String getPlayScreen() {
        return playScreen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_play.play_screen
     *
     * @param playScreen the value for t_play.play_screen
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public void setPlayScreen(String playScreen) {
        this.playScreen = playScreen == null ? null : playScreen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_play.play_video
     *
     * @return the value of t_play.play_video
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public String getPlayVideo() {
        return playVideo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_play.play_video
     *
     * @param playVideo the value for t_play.play_video
     *
     * @mbg.generated Wed Nov 18 02:00:18 CST 2020
     */
    public void setPlayVideo(String playVideo) {
        this.playVideo = playVideo == null ? null : playVideo.trim();
    }
}