package com.steven.television.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class TSupplier {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.supplier_id
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private String supplierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.supplier_name
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private String supplierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.supplier_addr
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private String supplierAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.supplier_phone
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private String supplierPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.supplier_desc
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private String supplierDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.status
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.create_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    @JsonFormat(locale="zh", timezone="GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.update_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    @JsonFormat(locale="zh", timezone="GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier.audit_status
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private Integer auditStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.supplier_id
     *
     * @return the value of t_supplier.supplier_id
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.supplier_id
     *
     * @param supplierId the value for t_supplier.supplier_id
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId == null ? null : supplierId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.supplier_name
     *
     * @return the value of t_supplier.supplier_name
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.supplier_name
     *
     * @param supplierName the value for t_supplier.supplier_name
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.supplier_addr
     *
     * @return the value of t_supplier.supplier_addr
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public String getSupplierAddr() {
        return supplierAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.supplier_addr
     *
     * @param supplierAddr the value for t_supplier.supplier_addr
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setSupplierAddr(String supplierAddr) {
        this.supplierAddr = supplierAddr == null ? null : supplierAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.supplier_phone
     *
     * @return the value of t_supplier.supplier_phone
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public String getSupplierPhone() {
        return supplierPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.supplier_phone
     *
     * @param supplierPhone the value for t_supplier.supplier_phone
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setSupplierPhone(String supplierPhone) {
        this.supplierPhone = supplierPhone == null ? null : supplierPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.supplier_desc
     *
     * @return the value of t_supplier.supplier_desc
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public String getSupplierDesc() {
        return supplierDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.supplier_desc
     *
     * @param supplierDesc the value for t_supplier.supplier_desc
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setSupplierDesc(String supplierDesc) {
        this.supplierDesc = supplierDesc == null ? null : supplierDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.status
     *
     * @return the value of t_supplier.status
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.status
     *
     * @param status the value for t_supplier.status
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.create_time
     *
     * @return the value of t_supplier.create_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.create_time
     *
     * @param createTime the value for t_supplier.create_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.update_time
     *
     * @return the value of t_supplier.update_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.update_time
     *
     * @param updateTime the value for t_supplier.update_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier.audit_status
     *
     * @return the value of t_supplier.audit_status
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier.audit_status
     *
     * @param auditStatus the value for t_supplier.audit_status
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }
}