package com.steven.television.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class TSystem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system.sys_id
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private String sysId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system.sys_key
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private String sysKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system.sys_value
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private String sysValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system.sys_desc
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    private String sysDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_system.sys_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    @JsonFormat(locale="zh", timezone="GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date sysTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system.sys_id
     *
     * @return the value of t_system.sys_id
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public String getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system.sys_id
     *
     * @param sysId the value for t_system.sys_id
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setSysId(String sysId) {
        this.sysId = sysId == null ? null : sysId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system.sys_key
     *
     * @return the value of t_system.sys_key
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public String getSysKey() {
        return sysKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system.sys_key
     *
     * @param sysKey the value for t_system.sys_key
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setSysKey(String sysKey) {
        this.sysKey = sysKey == null ? null : sysKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system.sys_value
     *
     * @return the value of t_system.sys_value
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public String getSysValue() {
        return sysValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system.sys_value
     *
     * @param sysValue the value for t_system.sys_value
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setSysValue(String sysValue) {
        this.sysValue = sysValue == null ? null : sysValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system.sys_desc
     *
     * @return the value of t_system.sys_desc
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public String getSysDesc() {
        return sysDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system.sys_desc
     *
     * @param sysDesc the value for t_system.sys_desc
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setSysDesc(String sysDesc) {
        this.sysDesc = sysDesc == null ? null : sysDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_system.sys_time
     *
     * @return the value of t_system.sys_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public Date getSysTime() {
        return sysTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_system.sys_time
     *
     * @param sysTime the value for t_system.sys_time
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setSysTime(Date sysTime) {
        this.sysTime = sysTime;
    }
}