package com.steven.television.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TTelevisionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public TTelevisionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTvIdIsNull() {
            addCriterion("tv_id is null");
            return (Criteria) this;
        }

        public Criteria andTvIdIsNotNull() {
            addCriterion("tv_id is not null");
            return (Criteria) this;
        }

        public Criteria andTvIdEqualTo(String value) {
            addCriterion("tv_id =", value, "tvId");
            return (Criteria) this;
        }

        public Criteria andTvIdNotEqualTo(String value) {
            addCriterion("tv_id <>", value, "tvId");
            return (Criteria) this;
        }

        public Criteria andTvIdGreaterThan(String value) {
            addCriterion("tv_id >", value, "tvId");
            return (Criteria) this;
        }

        public Criteria andTvIdGreaterThanOrEqualTo(String value) {
            addCriterion("tv_id >=", value, "tvId");
            return (Criteria) this;
        }

        public Criteria andTvIdLessThan(String value) {
            addCriterion("tv_id <", value, "tvId");
            return (Criteria) this;
        }

        public Criteria andTvIdLessThanOrEqualTo(String value) {
            addCriterion("tv_id <=", value, "tvId");
            return (Criteria) this;
        }

        public Criteria andTvIdLike(String value) {
            addCriterion("tv_id like", value, "tvId");
            return (Criteria) this;
        }

        public Criteria andTvIdNotLike(String value) {
            addCriterion("tv_id not like", value, "tvId");
            return (Criteria) this;
        }

        public Criteria andTvIdIn(List<String> values) {
            addCriterion("tv_id in", values, "tvId");
            return (Criteria) this;
        }

        public Criteria andTvIdNotIn(List<String> values) {
            addCriterion("tv_id not in", values, "tvId");
            return (Criteria) this;
        }

        public Criteria andTvIdBetween(String value1, String value2) {
            addCriterion("tv_id between", value1, value2, "tvId");
            return (Criteria) this;
        }

        public Criteria andTvIdNotBetween(String value1, String value2) {
            addCriterion("tv_id not between", value1, value2, "tvId");
            return (Criteria) this;
        }

        public Criteria andTvNameIsNull() {
            addCriterion("tv_name is null");
            return (Criteria) this;
        }

        public Criteria andTvNameIsNotNull() {
            addCriterion("tv_name is not null");
            return (Criteria) this;
        }

        public Criteria andTvNameEqualTo(String value) {
            addCriterion("tv_name =", value, "tvName");
            return (Criteria) this;
        }

        public Criteria andTvNameNotEqualTo(String value) {
            addCriterion("tv_name <>", value, "tvName");
            return (Criteria) this;
        }

        public Criteria andTvNameGreaterThan(String value) {
            addCriterion("tv_name >", value, "tvName");
            return (Criteria) this;
        }

        public Criteria andTvNameGreaterThanOrEqualTo(String value) {
            addCriterion("tv_name >=", value, "tvName");
            return (Criteria) this;
        }

        public Criteria andTvNameLessThan(String value) {
            addCriterion("tv_name <", value, "tvName");
            return (Criteria) this;
        }

        public Criteria andTvNameLessThanOrEqualTo(String value) {
            addCriterion("tv_name <=", value, "tvName");
            return (Criteria) this;
        }

        public Criteria andTvNameLike(String value) {
            addCriterion("tv_name like", value, "tvName");
            return (Criteria) this;
        }

        public Criteria andTvNameNotLike(String value) {
            addCriterion("tv_name not like", value, "tvName");
            return (Criteria) this;
        }

        public Criteria andTvNameIn(List<String> values) {
            addCriterion("tv_name in", values, "tvName");
            return (Criteria) this;
        }

        public Criteria andTvNameNotIn(List<String> values) {
            addCriterion("tv_name not in", values, "tvName");
            return (Criteria) this;
        }

        public Criteria andTvNameBetween(String value1, String value2) {
            addCriterion("tv_name between", value1, value2, "tvName");
            return (Criteria) this;
        }

        public Criteria andTvNameNotBetween(String value1, String value2) {
            addCriterion("tv_name not between", value1, value2, "tvName");
            return (Criteria) this;
        }

        public Criteria andTvDescIsNull() {
            addCriterion("tv_desc is null");
            return (Criteria) this;
        }

        public Criteria andTvDescIsNotNull() {
            addCriterion("tv_desc is not null");
            return (Criteria) this;
        }

        public Criteria andTvDescEqualTo(String value) {
            addCriterion("tv_desc =", value, "tvDesc");
            return (Criteria) this;
        }

        public Criteria andTvDescNotEqualTo(String value) {
            addCriterion("tv_desc <>", value, "tvDesc");
            return (Criteria) this;
        }

        public Criteria andTvDescGreaterThan(String value) {
            addCriterion("tv_desc >", value, "tvDesc");
            return (Criteria) this;
        }

        public Criteria andTvDescGreaterThanOrEqualTo(String value) {
            addCriterion("tv_desc >=", value, "tvDesc");
            return (Criteria) this;
        }

        public Criteria andTvDescLessThan(String value) {
            addCriterion("tv_desc <", value, "tvDesc");
            return (Criteria) this;
        }

        public Criteria andTvDescLessThanOrEqualTo(String value) {
            addCriterion("tv_desc <=", value, "tvDesc");
            return (Criteria) this;
        }

        public Criteria andTvDescLike(String value) {
            addCriterion("tv_desc like", value, "tvDesc");
            return (Criteria) this;
        }

        public Criteria andTvDescNotLike(String value) {
            addCriterion("tv_desc not like", value, "tvDesc");
            return (Criteria) this;
        }

        public Criteria andTvDescIn(List<String> values) {
            addCriterion("tv_desc in", values, "tvDesc");
            return (Criteria) this;
        }

        public Criteria andTvDescNotIn(List<String> values) {
            addCriterion("tv_desc not in", values, "tvDesc");
            return (Criteria) this;
        }

        public Criteria andTvDescBetween(String value1, String value2) {
            addCriterion("tv_desc between", value1, value2, "tvDesc");
            return (Criteria) this;
        }

        public Criteria andTvDescNotBetween(String value1, String value2) {
            addCriterion("tv_desc not between", value1, value2, "tvDesc");
            return (Criteria) this;
        }

        public Criteria andTvScreenIsNull() {
            addCriterion("tv_screen is null");
            return (Criteria) this;
        }

        public Criteria andTvScreenIsNotNull() {
            addCriterion("tv_screen is not null");
            return (Criteria) this;
        }

        public Criteria andTvScreenEqualTo(String value) {
            addCriterion("tv_screen =", value, "tvScreen");
            return (Criteria) this;
        }

        public Criteria andTvScreenNotEqualTo(String value) {
            addCriterion("tv_screen <>", value, "tvScreen");
            return (Criteria) this;
        }

        public Criteria andTvScreenGreaterThan(String value) {
            addCriterion("tv_screen >", value, "tvScreen");
            return (Criteria) this;
        }

        public Criteria andTvScreenGreaterThanOrEqualTo(String value) {
            addCriterion("tv_screen >=", value, "tvScreen");
            return (Criteria) this;
        }

        public Criteria andTvScreenLessThan(String value) {
            addCriterion("tv_screen <", value, "tvScreen");
            return (Criteria) this;
        }

        public Criteria andTvScreenLessThanOrEqualTo(String value) {
            addCriterion("tv_screen <=", value, "tvScreen");
            return (Criteria) this;
        }

        public Criteria andTvScreenLike(String value) {
            addCriterion("tv_screen like", value, "tvScreen");
            return (Criteria) this;
        }

        public Criteria andTvScreenNotLike(String value) {
            addCriterion("tv_screen not like", value, "tvScreen");
            return (Criteria) this;
        }

        public Criteria andTvScreenIn(List<String> values) {
            addCriterion("tv_screen in", values, "tvScreen");
            return (Criteria) this;
        }

        public Criteria andTvScreenNotIn(List<String> values) {
            addCriterion("tv_screen not in", values, "tvScreen");
            return (Criteria) this;
        }

        public Criteria andTvScreenBetween(String value1, String value2) {
            addCriterion("tv_screen between", value1, value2, "tvScreen");
            return (Criteria) this;
        }

        public Criteria andTvScreenNotBetween(String value1, String value2) {
            addCriterion("tv_screen not between", value1, value2, "tvScreen");
            return (Criteria) this;
        }

        public Criteria andTvLocationIsNull() {
            addCriterion("tv_location is null");
            return (Criteria) this;
        }

        public Criteria andTvLocationIsNotNull() {
            addCriterion("tv_location is not null");
            return (Criteria) this;
        }

        public Criteria andTvLocationEqualTo(String value) {
            addCriterion("tv_location =", value, "tvLocation");
            return (Criteria) this;
        }

        public Criteria andTvLocationNotEqualTo(String value) {
            addCriterion("tv_location <>", value, "tvLocation");
            return (Criteria) this;
        }

        public Criteria andTvLocationGreaterThan(String value) {
            addCriterion("tv_location >", value, "tvLocation");
            return (Criteria) this;
        }

        public Criteria andTvLocationGreaterThanOrEqualTo(String value) {
            addCriterion("tv_location >=", value, "tvLocation");
            return (Criteria) this;
        }

        public Criteria andTvLocationLessThan(String value) {
            addCriterion("tv_location <", value, "tvLocation");
            return (Criteria) this;
        }

        public Criteria andTvLocationLessThanOrEqualTo(String value) {
            addCriterion("tv_location <=", value, "tvLocation");
            return (Criteria) this;
        }

        public Criteria andTvLocationLike(String value) {
            addCriterion("tv_location like", value, "tvLocation");
            return (Criteria) this;
        }

        public Criteria andTvLocationNotLike(String value) {
            addCriterion("tv_location not like", value, "tvLocation");
            return (Criteria) this;
        }

        public Criteria andTvLocationIn(List<String> values) {
            addCriterion("tv_location in", values, "tvLocation");
            return (Criteria) this;
        }

        public Criteria andTvLocationNotIn(List<String> values) {
            addCriterion("tv_location not in", values, "tvLocation");
            return (Criteria) this;
        }

        public Criteria andTvLocationBetween(String value1, String value2) {
            addCriterion("tv_location between", value1, value2, "tvLocation");
            return (Criteria) this;
        }

        public Criteria andTvLocationNotBetween(String value1, String value2) {
            addCriterion("tv_location not between", value1, value2, "tvLocation");
            return (Criteria) this;
        }

        public Criteria andTvTypeIsNull() {
            addCriterion("tv_type is null");
            return (Criteria) this;
        }

        public Criteria andTvTypeIsNotNull() {
            addCriterion("tv_type is not null");
            return (Criteria) this;
        }

        public Criteria andTvTypeEqualTo(Integer value) {
            addCriterion("tv_type =", value, "tvType");
            return (Criteria) this;
        }

        public Criteria andTvTypeNotEqualTo(Integer value) {
            addCriterion("tv_type <>", value, "tvType");
            return (Criteria) this;
        }

        public Criteria andTvTypeGreaterThan(Integer value) {
            addCriterion("tv_type >", value, "tvType");
            return (Criteria) this;
        }

        public Criteria andTvTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("tv_type >=", value, "tvType");
            return (Criteria) this;
        }

        public Criteria andTvTypeLessThan(Integer value) {
            addCriterion("tv_type <", value, "tvType");
            return (Criteria) this;
        }

        public Criteria andTvTypeLessThanOrEqualTo(Integer value) {
            addCriterion("tv_type <=", value, "tvType");
            return (Criteria) this;
        }

        public Criteria andTvTypeIn(List<Integer> values) {
            addCriterion("tv_type in", values, "tvType");
            return (Criteria) this;
        }

        public Criteria andTvTypeNotIn(List<Integer> values) {
            addCriterion("tv_type not in", values, "tvType");
            return (Criteria) this;
        }

        public Criteria andTvTypeBetween(Integer value1, Integer value2) {
            addCriterion("tv_type between", value1, value2, "tvType");
            return (Criteria) this;
        }

        public Criteria andTvTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("tv_type not between", value1, value2, "tvType");
            return (Criteria) this;
        }

        public Criteria andTvLengthIsNull() {
            addCriterion("tv_length is null");
            return (Criteria) this;
        }

        public Criteria andTvLengthIsNotNull() {
            addCriterion("tv_length is not null");
            return (Criteria) this;
        }

        public Criteria andTvLengthEqualTo(Long value) {
            addCriterion("tv_length =", value, "tvLength");
            return (Criteria) this;
        }

        public Criteria andTvLengthNotEqualTo(Long value) {
            addCriterion("tv_length <>", value, "tvLength");
            return (Criteria) this;
        }

        public Criteria andTvLengthGreaterThan(Long value) {
            addCriterion("tv_length >", value, "tvLength");
            return (Criteria) this;
        }

        public Criteria andTvLengthGreaterThanOrEqualTo(Long value) {
            addCriterion("tv_length >=", value, "tvLength");
            return (Criteria) this;
        }

        public Criteria andTvLengthLessThan(Long value) {
            addCriterion("tv_length <", value, "tvLength");
            return (Criteria) this;
        }

        public Criteria andTvLengthLessThanOrEqualTo(Long value) {
            addCriterion("tv_length <=", value, "tvLength");
            return (Criteria) this;
        }

        public Criteria andTvLengthIn(List<Long> values) {
            addCriterion("tv_length in", values, "tvLength");
            return (Criteria) this;
        }

        public Criteria andTvLengthNotIn(List<Long> values) {
            addCriterion("tv_length not in", values, "tvLength");
            return (Criteria) this;
        }

        public Criteria andTvLengthBetween(Long value1, Long value2) {
            addCriterion("tv_length between", value1, value2, "tvLength");
            return (Criteria) this;
        }

        public Criteria andTvLengthNotBetween(Long value1, Long value2) {
            addCriterion("tv_length not between", value1, value2, "tvLength");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andSupplierIdIsNull() {
            addCriterion("supplier_id is null");
            return (Criteria) this;
        }

        public Criteria andSupplierIdIsNotNull() {
            addCriterion("supplier_id is not null");
            return (Criteria) this;
        }

        public Criteria andSupplierIdEqualTo(String value) {
            addCriterion("supplier_id =", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdNotEqualTo(String value) {
            addCriterion("supplier_id <>", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdGreaterThan(String value) {
            addCriterion("supplier_id >", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdGreaterThanOrEqualTo(String value) {
            addCriterion("supplier_id >=", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdLessThan(String value) {
            addCriterion("supplier_id <", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdLessThanOrEqualTo(String value) {
            addCriterion("supplier_id <=", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdLike(String value) {
            addCriterion("supplier_id like", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdNotLike(String value) {
            addCriterion("supplier_id not like", value, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdIn(List<String> values) {
            addCriterion("supplier_id in", values, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdNotIn(List<String> values) {
            addCriterion("supplier_id not in", values, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdBetween(String value1, String value2) {
            addCriterion("supplier_id between", value1, value2, "supplierId");
            return (Criteria) this;
        }

        public Criteria andSupplierIdNotBetween(String value1, String value2) {
            addCriterion("supplier_id not between", value1, value2, "supplierId");
            return (Criteria) this;
        }

        public Criteria andAuditStateIsNull() {
            addCriterion("audit_state is null");
            return (Criteria) this;
        }

        public Criteria andAuditStateIsNotNull() {
            addCriterion("audit_state is not null");
            return (Criteria) this;
        }

        public Criteria andAuditStateEqualTo(String value) {
            addCriterion("audit_state =", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateNotEqualTo(String value) {
            addCriterion("audit_state <>", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateGreaterThan(String value) {
            addCriterion("audit_state >", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateGreaterThanOrEqualTo(String value) {
            addCriterion("audit_state >=", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateLessThan(String value) {
            addCriterion("audit_state <", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateLessThanOrEqualTo(String value) {
            addCriterion("audit_state <=", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateLike(String value) {
            addCriterion("audit_state like", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateNotLike(String value) {
            addCriterion("audit_state not like", value, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateIn(List<String> values) {
            addCriterion("audit_state in", values, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateNotIn(List<String> values) {
            addCriterion("audit_state not in", values, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateBetween(String value1, String value2) {
            addCriterion("audit_state between", value1, value2, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditStateNotBetween(String value1, String value2) {
            addCriterion("audit_state not between", value1, value2, "auditState");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkIsNull() {
            addCriterion("audit_remark is null");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkIsNotNull() {
            addCriterion("audit_remark is not null");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkEqualTo(String value) {
            addCriterion("audit_remark =", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkNotEqualTo(String value) {
            addCriterion("audit_remark <>", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkGreaterThan(String value) {
            addCriterion("audit_remark >", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("audit_remark >=", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkLessThan(String value) {
            addCriterion("audit_remark <", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkLessThanOrEqualTo(String value) {
            addCriterion("audit_remark <=", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkLike(String value) {
            addCriterion("audit_remark like", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkNotLike(String value) {
            addCriterion("audit_remark not like", value, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkIn(List<String> values) {
            addCriterion("audit_remark in", values, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkNotIn(List<String> values) {
            addCriterion("audit_remark not in", values, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkBetween(String value1, String value2) {
            addCriterion("audit_remark between", value1, value2, "auditRemark");
            return (Criteria) this;
        }

        public Criteria andAuditRemarkNotBetween(String value1, String value2) {
            addCriterion("audit_remark not between", value1, value2, "auditRemark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_television
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 09 22:22:16 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_television
     *
     * @mbg.generated Mon Nov 09 22:22:16 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}